# Generated by Django 2.1.4 on 2019-02-20 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0020_auto_20190220_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 2, 20, 3, 22, 11, 596225))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfileInfo')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 20, 3, 22, 11, 596629))),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfileInfo')),
                ('comment', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.Comment')),
            ],
        ),
    ]
