# Generated by Django 2.1.4 on 2019-03-05 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190301_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 11, 41, 54, 862718)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 11, 41, 54, 925118)),
        ),
    ]
