# Generated by Django 2.1.4 on 2019-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_icon', models.ImageField(upload_to='icons')),
                ('site_logo', models.ImageField(upload_to='logos')),
                ('site_title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('post_per_page', models.IntegerField(default=5)),
            ],
        ),
    ]
