# Generated by Django 2.1.4 on 2019-01-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategoried', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_img',
            field=models.ImageField(blank=True, upload_to='featured_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='sql', max_length=100),
        ),
    ]
