# Generated by Django 2.1.4 on 2019-01-29 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190129_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 29, 0, 19, 33, 377347)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 0, 19, 33, 376844)),
        ),
    ]
