# Generated by Django 2.1.4 on 2019-01-30 00:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190129_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 30, 0, 26, 46, 9114))),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfileInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 30, 0, 26, 46, 8660)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 0, 26, 46, 8220)),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment'),
        ),
    ]
